### ISSUE TITLE
Still under heavy development?

### ISSUE THREAD

**Issue by nicoguaro** [verdverm/pypge#11]

**Comment by sohrabtowfighi** [comment]
Would it be possible to get a simple working example?

**Comment by verdverm** [comment]
This is not under any development. My time is required elsewhere. Sorry

**Comment by sohrabtowfighi** [comment]
Fair enough, but I spent a lot of time trying to figure out whether your previous release worked. If you ever get some spare time, pointing us to a working version of your code would ensure your work can be used by the SR community.

**Comment by verdverm** [comment]
If someone could find some funding, that would enable me to take time off to develop this project.

Would anyone be interested in sponsoring?

**Comment by sohrabtowfighi** [comment]
Didn't you write your dissertation on this? Presumably that was funded. Anyways, your project will end up relegated to the realm of abandonware.

**Comment by verdverm** [comment]
That was 3 years ago, new development would require new funding.

Happy to setup an open collective and funding.md

**Comment by pySRURGS** [comment]
Go for it. I'd put in 10 bucks CAD.

**Comment by sohrabtowfighi** [comment]
I would be willing to give you 10$ CAD to fix your own PhD project. Commence the open collective.

**Comment by verdverm** [comment]
The goal would have to be in the $X,000s to cover sufficient hours to make this a reality. Or maybe we could hire some freelancers or put up a bounty with the funding?

p.s. saying things like the following is off putting and not helping to achieve your desired outcomes.

> I would be willing to give you 10$ CAD to fix your own PhD project

If it's important enough to you, you would put in the time to go through the readme, file a bug report, and open a PR.

**Comment by sohrabtowfighi** [comment]
I went through every single python code file in pypge. You did not write much by way of comments. Your simple use cases are broken. There are massive code blocks that are commented out. This is too messy for someone who wasn't embedded in the work to resolve.

**Comment by verdverm** [comment]
Yup, not surprised by most of that.

**Comment by verdverm** [comment]
you could ask the poster of https://github.com/verdverm/pypge/issues/12 

They were able to get PyPGE running

**Comment by verdverm** [comment]
@sohrabtowfighi You have a mistake in your recent paper, apparently the code still works as others have been able to use it. Thanks for the shout out, even if it was a snide one!
