### ISSUE TITLE
AttributeError: 'PGE' object has no attribute 'multi_expander_params'

### ISSUE THREAD

**Issue by embg** [verdverm/pypge#5]
I've had several issues trying to get `PGE.fit` to work. I was able to fix all the ones I've had so far, and intend to submit a PR, but can't figure out this one. There's code in `search.py` that uses `self.multi_expander_params`, but the object doesn't have that attribute! I assume it was defined in the past and then taken out. I'm not sure if it's safe to remove the code that uses the `multi_expander_params`, so I wanted to submit an issue and ask how best to fix this problem.

Steps to reproduce: define a valid `pypge.search.PGE` object, run its `fit` method, get other errors, fix those, get this error.

I have tested this on main and develop branches, I get the error on both.

**Comment by embg** [comment]
Fixed: I added 

```
    self.multi_expander_params = [{'pop_count':self.pop_count,
                           'usable_funcs':self.usable_funcs,
                           'grow_params':self.grow_params}]
```

to the PGE class. I'll include this in my PR. I'm going to leave this issue open because I'm sure there's a better way to fix this, and I'm curious what `multi_expander_params` are.

**Comment by verdverm** [comment]
You should set these in the config file, not the pypge package code
